
# Header
menu:
  博客首页: /
  JAVA新手入门: /tags/新手入门/page/2/
  全部文章: /archives
  关于双King: /about
  WEB开发: /web-need-know/


# Content
excerpt_link: 查看全部
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

##  这里开始是主题配置信息  ##

# Links
links:
  美团技术博客: https://tech.meituan.com/
  阿土的博客: http://gobue.com/
  晓刚的博客: http://www.cnblogs.com/xiaogangfan
  toukii的Go语言: http://mdblog.daoapp.io/
  酷壳: https://coolshell.cn/

# Miscellaneous

google_analytics:
favicon: /img/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

##  这里开始是主题配置信息  ##
gitalk:
  enable: false
  owner: husd
  admin: husd
  repo: husd.github.io
  ClientID: xx
  ClientSecret: xx
  labels: 'gitalk'
  distractionFreeMode: true
